config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"

  resource :welcome, only: [:index]
  resources :tournaments, only: [:new, :create, :show]
  resources :fifa_teams, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fifa_team.rb
class FifaTeam < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :league
  validates_presence_of :attack
  validates_presence_of :midfield
  validates_presence_of :defense
  validates_presence_of :overall
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home_team, class_name: 'User'
  belongs_to :away_team, class_name: 'User'
  belongs_to :home_fifa_team, class_name: 'FifaTeam'
  belongs_to :away_fifa_team, class_name: 'FifaTeam'
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :games
end

app/models/user.rb
class User < ApplicationRecord
  # Easiest way to do the association
  def games
    Game.where("home_team_id = ? OR away_team_id = ?", self.id, self.id)
  end

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  validates :email,
            uniqueness: true,
            presence: true
  validates :username,
            uniqueness: true,
            presence: true

  attr_accessor :login

  # Add support for authenticate with both email and username
  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ["lower(username) = :value OR lower(email) = :value",
      { value: login.strip.downcase}]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:username, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:login, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update,
        keys: [:username, :email, :password_confirmation, :current_password])
    end
end

app/controllers/fifa_teams_controller.rb
class FifaTeamsController < ApplicationController
  def index
    @leagues = FifaTeam.where("league #{gender_clause} ILIKE ?", "%Women%").distinct.pluck(:league)
    render json: @leagues
  end

  private

  def gender_clause
    params[:gender] == 'women' ? "" : "NOT"
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def new
    @users = User.all
  end

  def create
    @tournament = Tournament.new(name: params[:name])
    generated_games.each do |game|
      @tournament.games.build(home_team_id: game[0], away_team_id: game[1], round: game[2], tournament: @tournament)
    end

    if @tournament.save
      redirect_to tournament_path @tournament
    else
      render 'new'
    end
  end

  def show
    @tournament = Tournament.find(params[:id])

    per_page = @tournament.games.where(round: 1).count
    round_page = params[:page].present? ? params[:page] : upcoming_game_page(@tournament.games)

    @table = ActiveRecord::Base.connection.execute(table_query)
    @games = @tournament.games.order('round ASC').page(round_page).per_page(per_page)
  end

  private

  def upcoming_game_page(games)
    games.find{ |game| game.home_team_score.nil? || game.away_team_score.nil?}.round
  end

  def generated_games
    @generated_games ||= TournamentGenerator.new(params[:user_ids].reject(&:empty?), params[:rounds]).generate_games
  end

  def table_query
    <<-EOF
      WITH users_games_with_score AS (
        SELECT
            users.username,
            CASE
              WHEN users.id = home_team_id THEN home_team_score
              WHEN users.id = away_team_id THEN away_team_score
            END as scored_goals,
            CASE
              WHEN users.id = home_team_id THEN away_team_score
              WHEN users.id = away_team_id THEN home_team_score
            END as conceded_goals
        FROM
          tournaments
        JOIN
          games
        ON
          tournaments.id = games.tournament_id
        JOIN
          users
        ON
          users.id = games.home_team_id OR users.id = games.away_team_id
        WHERE
          tournaments.id = #{params[:id]}
      ), user_games_with_points AS(
        SELECT
          *,
          CASE
            WHEN scored_goals > conceded_goals THEN 3
            WHEN scored_goals = conceded_goals THEN 1
            ELSE 0
          END as points
        FROM
          users_games_with_score
      )

      SELECT
        username,
        COUNT(*) filter(WHERE scored_goals IS NOT NULL AND conceded_goals IS NOT NULL) played_games,
        COUNT(*) filter(WHERE scored_goals > conceded_goals) won_games,
        COUNT(*) filter(WHERE scored_goals = conceded_goals AND scored_goals IS NOT NULL AND conceded_goals IS NOT NULL) tied_games,
        COUNT(*) filter(WHERE scored_goals < conceded_goals) lost_games,
        SUM(CASE WHEN scored_goals IS NULL THEN 0 ELSE scored_goals END) as scored_goals,
        SUM(CASE WHEN conceded_goals IS NULL THEN 0 ELSE conceded_goals END) as conceded_goals,
        (SUM(CASE WHEN scored_goals IS NULL THEN 0 ELSE scored_goals END) - SUM(CASE WHEN conceded_goals IS NULL THEN 0 ELSE conceded_goals END)) as goal_difference,
        SUM(points) as points
      FROM
        user_games_with_points
      GROUP BY
        username
      ORDER BY
        9 DESC,
        8 DESC,
        6 DESC
    EOF
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: var(--dark-green)">
  <div class="container">
    <a class="navbar-brand" href="#" style="color: white;">Tournamentify</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo" aria-controls="navbarTogglerDemo" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "Profile", edit_user_registration_path, :method => :get %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, :method => :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= button_to "Sign in", new_user_session_path, :method => :get %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tournamentify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Slim select -->
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class="container">
      <!-- Devise -->
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <!-- Devise -->

      <%= yield %>
    </div>
  </body>
</html>

app/views/tournaments/new.html.erb
<div class="wrapper col-box">
  <h1>Create tournament</h1>


  <%= form_with url: tournaments_path, method: :post do |form| %>
    <%= form.text_field :name, placeholder: "Namn", required: true %>

    <%= form.select :user_ids, User.pluck(:username, :id), {}, {multiple: true, include_blank: false, data: {controller: "slim"}} %>

    <%= form.number_field :rounds, min: 1, value: 1 %>
    <%= form.submit "Create" %>
  <% end %>
</div>

app/views/tournaments/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Lag</th>
      <th scope="col">SM</th>
      <th scope="col">VM</th>
      <th scope="col">OM</th>
      <th scope="col">FM</th>
      <th scope="col">GM</th>
      <th scope="col">IM</th>
      <th scope="col">MS</th>
      <th scope="col">P</th>
    </tr>
  </thead>
  <tbody>
    <% @table.each_with_index do |row, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= row["username"] %></td>
        <td><%= row["played_games"] %></td>
        <td><%= row["won_games"] %></td>
        <td><%= row["tied_games"] %></td>
        <td><%= row["lost_games"] %></td>
        <td><%= row["scored_goals"] %></td>
        <td><%= row["conceded_goals"] %></td>
        <td><%= row["goal_difference"] %></td>
        <td><%= row["points"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<% @games.each do |game| %>
  <div class="col col-box">
    <h5 style="text-align: center"><%= game.home_team.username %> -  <%= game.away_team.username %></h5>
    <p style="text-align: center"><%= game.home_fifa_team %> -  <%= game.away_fifa_team %></p>
    <h6 style="text-align: center"><%= game.home_team_score.present? ? game.home_team_score : 0 %> -  <%= game.away_team_score.present? ? game.away_team_score : 0 %></h6>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Slumpa lag
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog col-box">
        <div class="modal-content" style="background-color: transparent;">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">

            <div class="input-group mb-3">
              <input type="number" class="form-control" placeholder="Minimum stars" aria-label="Server" min="0" max="5" step="0.5">
              <input type="number" class="form-control" placeholder="Maxiumum stars" aria-label="Username" min="0" max="5" step="0.5">
            </div>


          </div>


          <%= form_with url: tournaments_path, method: :post do |form| %>
          <div class="input-group mb-3">
            <%= form.select :leagues, FifaTeam.where("league NOT ILIKE ?", "%Women%").distinct.pluck(:league), {}, {multiple: true, include_blank: false, data: {controller: "fifa_team"}} %>
          </div>
          <% end %>


            <div data-controller="fifa-team">
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="gender" id="men" value="men" data-fifa-team-target="radio" checked>
                <label class="form-check-label" for="men">Men</label>
              </div>

              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="gender" id="women" value="women" data-fifa-team-target="radio">
                <label class="form-check-label" for="women">Women</label>
              </div>
            </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>


  </div>
<% end %>

<%= will_paginate @games %>

app/views/welcome/index.html.erb
<div class="d-flex justify-content-between">
  <div style="width: 300px;">
    <%= render "welcome/partials/profile" %>
  </div>

  <div style="width: calc(100% - 320px);">
    <%= render "welcome/partials/tabs" %>
  </div>
</div>


<!--
  <div class="d-flex justify-content-center">
    <%= link_to "Create tournament", "#", class: "btn btn-primary" %>
    <%= link_to "Create game", "#", class: "btn btn-secondary" %>
  </div>
-->

<!--
  <div class="row">
    <div class="col-lg-4 no-padding-left">
      <div class="col col-box latest-game">
        <h5>Latest game</h5>
        <hr />

        <div class="row no-margin">
          <div class="col-2 score">
            <p>3</p>
          </div>

          <div class="col-10 team" style="align-items: center">
            <p>perjespersson</p>
          </div>
        </div>

        <div class="row no-margin">
          <div class="col-2 score">
            <p>1</p>
          </div>

          <div class="col-10 team">
            <p>fjunemeister</p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="col col-box">
        <h5>Latest Tournament</h5>
        <hr />

        <p>0 - 3</p>
      </div>
    </div>

    <div class="col-lg-4 no-padding-right">
      <div class="col col-box">
        <h5>Latest Tournament</h5>
        <hr />

        <p>0 - 3</p>
      </div>
    </div>
  </div>
  -->

<!--
  <div class="row" style="background-color: var(--light-green)">
    <h3>THIS IS A TEST</h3>
    <h4>THIS IS A TEST</h4>
    <h3>THIS IS A TEST</h3>
    <h4>THIS IS A TEST</h4>
  </div>
  -->

app/views/welcome/partials/_goal_difference.html.erb
<h6 style="margin-left: 20px; padding-top: 20px; margin-bottom: 0; font-size: 26px; font-weight: 300;">Goal difference</h6>
<p style="font-size: 60px; margin-top: -5px; margin-left: 20px; padding-top: 0px; margin-bottom: 0;">+13</p>
<p style="margin-left: 20px; padding-bottom: 20px; margin-top: -10px; font-weight: 300;">123/110</p>

app/views/welcome/partials/_latest_game.html.erb
<h6 style="margin-left: 20px; padding-top: 20px; margin-bottom: 0; font-size: 26px; font-weight: 300;">Latest game</h6>

<div class="d-flex" style="margin-top: 15px; align-items: center;">
  <div style="width: 90px;">
    <%= image_tag "https://media-exp1.licdn.com/dms/image/C4E03AQGbwKzAEOvEQw/profile-displayphoto-shrink_800_800/0/1616091200685?e=1670457600&v=beta&t=ptcCFukzOKp-FOR4K7_MwgY4dnB8GHheGEsI5sVpL0c", :style => "display: block; max-width: 50px; margin: 0 auto; border-radius: 50%;" %>
  </div>

  <div style="width: calc(100% - 180px);">
    <p style="margin-bottom: 0px; font-size: 18px; font-weight: 500;">FC jsper United</p>
  </div>

  <div style="width: 89px;">
    <p style="margin-bottom: 0px; font-weight: 500; font-size: 36px; text-align: center;">3</p>
  </div>
</div>

<div class="d-flex" style="margin-top: 15px; padding-bottom: 15px; align-items: center;">
  <div style="width: 90px;">
    <%= image_tag "https://media-exp1.licdn.com/dms/image/C4D03AQFNHfzPWMfVFA/profile-displayphoto-shrink_800_800/0/1582667219303?e=1671062400&v=beta&t=nR6uzUbsgz10ayqaUdJvWG-E7xhefS6Mju79Jk_IsLY", :style => "display: block; max-width: 50px; margin: 0 auto; border-radius: 50%;" %>
  </div>

  <div style="width: calc(100% - 180px);">
    <p style="margin-bottom: 0px; font-size: 18px;">Fjune If</p>
  </div>

  <div style="width: 89px;">
    <p style="margin-bottom: 0px; font-weight: 500; font-size: 36px; text-align: center;">2</p>
  </div>
</div>

app/views/welcome/partials/_latest_tournament.html.erb
<h6 style="margin-left: 20px; padding-top: 20px; margin-bottom: 0; font-size: 26px; font-weight: 300;">Latest tournament</h6>



  <div class="row" style="align-items: center; padding: 20px 0;">
    <div class="col-lg-4">
      <p style="text-align: center; font-weight: 500; font-size: 32px; margin-bottom: -5px;">+13</p>
      <p style="text-align: center">Goals</p>
    </div>

    <div class="col-lg-4" style="background-image: url('<%= image_path("trophy.png") %>'); background-repeat: no-repeat, repeat; background-size: 120px; background-position: center;" >
      <p style="text-align: center; font-weight: 500; font-size: 52px; padding-top: 10px; padding-bottom: 18px; margin-top: -8px;">2</p>
    </div>

    <div class="col-lg-4">
      <p style="text-align: center; font-weight: 500; font-size: 32px; margin-bottom: -5px;">12</p>
      <p style="text-align: center">Points</p>
    </div>
  </div>

app/views/welcome/partials/_profile.html.erb
<div class="col-box">

  <div style="padding-top: 20px">
    <%= image_tag "https://media-exp1.licdn.com/dms/image/C4E03AQGbwKzAEOvEQw/profile-displayphoto-shrink_800_800/0/1616091200685?e=1670457600&v=beta&t=ptcCFukzOKp-FOR4K7_MwgY4dnB8GHheGEsI5sVpL0c", :style => "display: block; max-width: 200px; margin: 0 auto; border-radius: 50%;" %>
  </div>

  <b><p style="text-align: center; font-size: 20px; margin: 0; margin-top: 15px;">fjunemeister</p></b>

  <p style="text-align: center; font-size: 16px; margin: 0; padding-bottom: 20px;">perjespersson@gmail.com</p>

</div>

<div class="col-box" style="padding: 0px 15px; margin-top: 20px">
  <%= link_to "NEW TOURNAMENT", new_tournament_path, style: "btn btn-primary full-width-btn" %>
  <button type="button" class="btn btn-primary full-width-btn" style="margin-top: 15px; margin-bottom: 0px; background: #016d9e;">NEW TOURNAMENT</button>
  <button type="button" class="btn btn-primary full-width-btn" style="margin: 15px 0; background: #016d9e;">NEW GAME</button>
</div>

app/views/welcome/partials/_statistics.html.erb
<div class="col-lg-4">
  <div class="col col-box">
    <%= render "welcome/partials/winning_rate" %>
  </div>
</div>

<div class="col-lg-4">
  <div class="col col-box">
    <%= render "welcome/partials/trophies" %>
  </div>
</div>

<div class="col-lg-4">
  <div class="col col-box">
    <%= render "welcome/partials/goal_difference" %>
  </div>
</div>

<div class="col-lg-6" style="margin-top: 10px;">
  <div class="col col-box">
    <%= render "welcome/partials/latest_game" %>
  </div>
</div>

<div class="col-lg-6" style="margin-top: 10px;">
  <div class="col col-box">
    <%= render "welcome/partials/latest_tournament" %>
  </div>
</div>

app/views/welcome/partials/_tabs.html.erb
<ul class="nav nav-pills d-flex justify-content-center col-box" id="pills-tab" role="tablist" style="margin-bottom: 20px">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-statistics" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">STATISTICS</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-settings" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">SETTINGS</button>
  </li>
</ul>

<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active row" id="pills-statistics" role="tabpanel" aria-labelledby="pills-statistics-tab">
    <%= render "welcome/partials/statistics" %>
  </div>

  <div class="row tab-pane fade" id="pills-settings" role="tabpanel" aria-labelledby="pills-settings-tab">
    Ju
  </div>
</div>

app/views/welcome/partials/_trophies.html.erb
<h6 style="margin-left: 20px; padding-top: 20px; margin-bottom: 0; font-size: 26px; font-weight: 300;">Trophies</h6>
<p style="font-size: 60px; margin-top: -5px; margin-left: 20px; padding-top: 0px; margin-bottom: 0;">3</p>
<p style="margin-left: 20px; padding-bottom: 20px; margin-top: -10px; font-weight: 300;">3/21</p>

app/views/welcome/partials/_winning_rate.html.erb
<h6 style="margin-left: 20px; padding-top: 20px; margin-bottom: 0; font-size: 26px; font-weight: 300;">Winning rate</h6>
<p style="font-size: 60px; margin-top: -5px; margin-left: 20px; padding-top: 0px; margin-bottom: 0;">75%</p>
<p style="margin-left: 20px; padding-bottom: 20px; margin-top: -10px; font-weight: 300;">113 wins</p>

<!--
<div class="progress" style="margin: 30px 20px; height: 30px;">
  <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<div class="d-flex justify-content-center" style="padding-bottom: 20px;">
  <div>
    <div style="border-radius: 50%; width: 10px; height: 10px; background: red; display: block; margin: 0 auto;">
    </div>
    <p style="margin: 0px 10px;">Wins</p>
  </div>

  <div>
    <div style="border-radius: 50%; width: 10px; height: 10px; background: green; display: block; margin: 0 auto;">
    </div>
    <p style="margin: 0px 10px;">Draws</p>
  </div>

  <div>
    <div style="border-radius: 50%; width: 10px; height: 10px; background: blue; display: block; margin: 0 auto;">
    </div>
    <p style="margin: 0px 10px;">Losses</p>
  </div>
</div>
-->